with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "mocks/{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/hbomb79/Thea/internal/ingest:
    interfaces:
      Searcher:
      Scraper:
      DataStore:

