with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/hbomb79/Thea/internal/ingest:
    config:
      dir: "../../internal/ingest/mocks"
    interfaces:
      Searcher:
      Scraper:
      DataStore:

