# Change these variables as necessary.
BINARY_NAME := thea

# ==================================================================================== #
# HELPERS
# ==================================================================================== #

.PHONY: configure-hooks
configure-hooks:
	@git config --local core.hooksPath .githooks/

## help: print this help message
.PHONY: help
help:
	@echo 'Usage:'
	@sed -n 's/^##//p' ${MAKEFILE_LIST} | column -t -s ':' |  sed -e 's/^/ /'

.PHONY: confirm
confirm:
	@echo -n 'Are you sure? [y/N] ' && read ans && [ $${ans:-N} = y ]

.PHONY: no-dirty
no-dirty:
	git diff --exit-code


# ==================================================================================== #
# QUALITY CONTROL
# ==================================================================================== #

## tidy: format code and tidy modfile
.PHONY: tidy
tidy:
	go fmt ./...
	go mod tidy -v
	go mod verify

## lint: run linting of src and go mod using std tools and golangci-lint
.PHONY: lint
lint:
	go vet ./...
# go run honnef.co/go/tools/cmd/staticcheck@latest -f stylish -checks=all,-ST1000,-U1000 ./...
	golangci-lint run

## audit: run quality control checks (tidy, lints, builds, checks for dep vulns and runs tests)
.PHONY: audit
audit: build tidy lint
	go run golang.org/x/vuln/cmd/govulncheck@latest ./...
	go test -buildvcs -vet=off ./...

.PHONY: test
test: build
	go test --count=1 -p=1 -v ./...

# ==================================================================================== #
# DEVELOPMENT
# ==================================================================================== #

## clean: remove existing artifcats generated by this makefile (.bin)
.PHONY: clean
clean:
	rm -rf ./.bin/

## build: build the application
.PHONY: build
build: configure-hooks
	go generate ./...
	go build -o=.bin/${BINARY_NAME}

## run: run the  application
.PHONY: run
run: build
	.bin/${BINARY_NAME}

## run/live: run the application with reloading on file changes
.PHONY: run/live
run/live:
	go run github.com/makiuchi-d/arelo@latest \
	--pattern '**/*.go' \
	--pattern '**/*.yaml' \
	--pattern '**/*.tmpl' \
	--ignore '**/*.gen.go' \
	--ignore '**/mocks/*' \
	-- make run

# ==================================================================================== #
# GIT HOOKS
# ==================================================================================== #

.PHONY: pre-commit
pre-commit: lint

.PHONY: pre-push
pre-push: audit
