package api

import (
	"github.com/hbomb79/Thea/internal/api/auth"
	"github.com/hbomb79/Thea/internal/api/ingests"
	"github.com/hbomb79/Thea/internal/api/medias"
	"github.com/hbomb79/Thea/internal/api/targets"
	"github.com/hbomb79/Thea/internal/api/transcodes"
	"github.com/hbomb79/Thea/internal/api/users"
	"github.com/hbomb79/Thea/internal/api/workflows"
)

// serverImpl offers an implementation of the generated
// ServerInterface (generated by OpenAPI).
type serverImpl struct {
	*ingests.IngestsController
	*auth.AuthController
	*users.UserController
	*medias.MediaController
	*transcodes.TranscodesController
	*targets.TargetController
	*workflows.WorkflowController
}

func newServerImpl(
	ingestController *ingests.IngestsController,
	transcodeController *transcodes.TranscodesController,
	targetsController *targets.TargetController,
	workflowController *workflows.WorkflowController,
	mediaController *medias.MediaController,
	userController *users.UserController,
	authController *auth.AuthController,
) *serverImpl {
	return &serverImpl{ingestController, authController, userController, mediaController, transcodeController, targetsController, workflowController}
}
